services:
# Qdrant service for vector search and storage
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
# Prometheus service for monitoring the Qdrant instance
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      # Volume for Prometheus data and configuration
      - prometheus_data:/prometheus 
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 512M

# Canary service for testing the Qdrant instance and Prometheus monitoring
  canary:
    image: python:3.11-slim
    container_name: canary_script
    depends_on:
      - qdrant
    environment:
      - CURL_CA_BUNDLE=
      - REQUESTS_CA_BUNDLE=
    volumes:
      - .:/app
      - pip_cache:/root/.cache/pip
      - hf_cache:/root/.cache/huggingface
    working_dir: /app
    command: >
      sh -c "pip install -r requirements.txt && python canary.py"

volumes:
  qdrant_data:
  prometheus_data:
  pip_cache:
  hf_cache: